# Change these first
owner: toonshouin # Your GitHub organization or username, where this repository lives
repo: site-status # The name of this repository

sites:
  - name: Main Site.
    url: https://toonshou.in
  - name: Linktree.
    url: https://card.toonshou.in
  - name: Blog Site.
    url: https://blog.toonshou.in
  - name: Resume site.
    url: https://resume.toonshou.in
  - name: Retro Site.
    url: http://legacy.toonshou.in
  - name: Hackclub Scrapbook.
    url: https://scrapbook.toonstorytime.me
  - name: Homelab (Direct)
    url: http://storyhouseproduction.duckdns.org
  - name: File Server (NAS)
    url: https://cloud.toonstorytime.me
  - name: Bitwarden
    url: https://pass.aoeyoei.xyz
  - name: Immich Server
    url: https://img.toonshou.in
  - name: Bluesky PDS
    url: https://blue.toonshou.in
  - name: Speedtest (Homelab)
    url: https://speed.aoeyoei.xyz
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.toonshou.in
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Toonshouin's Status Sites."
  introTitle: "Welcome to **Toonshouin's Status Sites!**."
  introMessage: "This status page will show status of all of the sites avaliable in Toonshouin's Studio and Project that I made. You can check using **this site** or on the [**Github Repository**](https://github.com/toonshouin/site-uptime) at the top. In the meanwhile, You can have some cookies right here. 🍪🍪"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
