# Change these first
owner: toonoeichi # Your GitHub organization or username, where this repository lives
repo: site-uptime # The name of this repository

sites:
  - name: Main Site.
    url: https://toonstorytime.me
  - name: Linktree.
    url: https://tree.toonstorytime.me
  - name: Blog Site.
    url: https://blog.toonstorytime.me
  - name: Resume site.
    url: https://resume.toonstorytime.me
  - name: Retro Site.
    url: https://toonnongaeoy.dino.icu
  - name: Hackclub Scrapbook.
    url: https://scrapbook.toonstorytime.me
  - name: Homelab (Direct)
    url: http://storyhouseproduction.duckdns.org
  - name: Homelab (VPN)
    url: https://vpn.toonstorytime.me
  - name: File Server (NAS)
    url: https://cloud.toonstorytime.me
  - name: Bitwarden
    url: https://pass.aoeyoei.xyz
  - name: Whoogle
    url: https://gle.aoeyoei.xyz
  - name: n8n
    url: https://n8.aoeyoei.xyz
  - name: Bluesky PDS
    url: https://bluesky.toonstorytime.me
  - name: Remote Desktop (Site)
    url: https://remdesk.toonstorytime.me
  - name: Remote Desktop
    check: "tcp-ping"
    url: remdesk.toonstorytime.me
    port: 3389
  - name: Speedtest (Homelab)
    url: https://speedtest.toonstorytime.me
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.toonstorytime.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "ToonStoryTime (ToonOeichi)'s Status Sites."
  introTitle: "Welcome to **ToonStoryTime (ToonOeichi)'s Status Sites!**."
  introMessage: "This status page will show status of all of the sites avaliable in ToonOeichi's Studio and Project that I made. You can check using **this site** or on the [**Github Repository**](https://github.com/toonoeichi/site-uptime) at the top. In the meanwhile, You can have some cookies right here. 🍪🍪"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
